version: '3'
services:
  peng_picture:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_SWOOLE_VERSION: ${PHP72_SWOOLE_VERSION}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    ports:
      - 9510:9501
    volumes:
      - ./:/var/www/peng_picture
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["php", "/var/www/peng_picture/easyswoole", "start"]
    networks:
      - default

networks:
  default: